// next-drawio-vue/src/components/PropertyPanel.vue
<template>
  <div class="w-full h-full p-4 bg-white border-l border-gray-200 shadow-lg flex flex-col">
    <h3 class="mb-4 text-sm font-medium text-gray-700">属性面板</h3>

    <div v-if="!selectedShape" class="text-sm text-gray-400">
      请选择一个形状以编辑属性
    </div>

    <div v-else class="flex-1 overflow-y-auto min-h-0">
      <!-- 标签页切换 -->
      <div class="flex p-1 mb-4 space-x-1 bg-gray-100 rounded">
        <button
          v-for="currentTab in ['style', 'text', 'shape']"
          :key="currentTab"
          @click="handleTabChange(currentTab)"
          :class="[
            'flex-1 py-1 px-2 text-xs font-medium rounded transition-colors',
            tab === currentTab ? 'bg-white text-gray-900 shadow' : 'text-gray-600 hover:text-gray-900'
          ]"
        >
          {{ tabLabels[currentTab] }}
        </button>
      </div>

      <!-- 样式标签页 -->
      <div v-if="tab === 'style'" class="space-y-3">
        <!-- 填充颜色 -->
        <div>
          <label class="block mb-1 text-xs font-medium text-gray-700">
            <div class="flex items-center justify-between">
              <span>填充颜色</span>
              <input
                type="checkbox"
                v-model="fillEnabled"
                @change="handleFillChange(fillEnabled ? currentFillColor : 'transparent')"
                class="w-3 h-3"
              />
            </div>
          </label>
          <div class="flex items-center space-x-2">
            <input
              type="color"
              v-model="currentFillColor"
              @input="handleFillChange(handleInputValue($event))"
              :disabled="!fillEnabled"
              class="w-8 h-8 border-0 rounded cursor-pointer"
            />
            <input
              type="text"
              v-model="currentFillColor"
              @input="handleFillChange(handleInputValue($event))"
              :disabled="!fillEnabled"
              class="flex-1 h-8 px-2 text-xs border border-gray-300 rounded"
            />
          </div>
        </div>

        <!-- 描边颜色 -->
        <div>
          <label class="block mb-1 text-xs font-medium text-gray-700">
            <div class="flex items-center justify-between">
              <span>描边颜色</span>
              <input
                type="checkbox"
                v-model="strokeEnabled"
                @change="handleStrokeWidthChange(strokeEnabled ? currentStrokeWidth : 0)"
                class="w-3 h-3"
              />
            </div>
          </label>
          <div class="flex items-center space-x-2">
            <input
              type="color"
              v-model="currentStrokeColor"
              @input="handleStrokeChange(handleInputValue($event))"
              :disabled="!strokeEnabled"
              class="w-8 h-8 border-0 rounded cursor-pointer"
            />
            <input
              type="text"
              v-model="currentStrokeColor"
              @input="handleStrokeChange(handleInputValue($event))"
              :disabled="!strokeEnabled"
              class="flex-1 h-8 px-2 text-xs border border-gray-300 rounded"
            />
          </div>
        </div>

        <!-- 描边宽度 -->
        <div>
          <label class="block mb-1 text-xs font-medium text-gray-700">
            描边宽度
          </label>
          <div class="flex items-center space-x-2">
            <input
              type="range"
              min="0"
              max="20"
              v-model.number="currentStrokeWidth"
              @input="handleStrokeWidthChange(handleInputNumber($event))"
              :disabled="!strokeEnabled"
              class="flex-1"
            />
            <span class="w-8 text-xs text-right text-gray-600">{{ currentStrokeWidth }}</span>
          </div>
        </div>

        <!-- 旋转 -->
        <div>
          <label class="block mb-1 text-xs font-medium text-gray-700">
            旋转角度
          </label>
          <div class="flex items-center space-x-2">
            <input
              type="range"
              min="0"
              max="360"
              v-model.number="currentRotation"
              @input="handleRotationChange(handleInputNumber($event))"
              class="flex-1"
            />
            <span class="w-8 text-xs text-right text-gray-600">{{ currentRotation }}°</span>
          </div>
        </div>

        <!-- 缩放 -->
        <div>
          <label class="block mb-1 text-xs font-medium text-gray-700">
            缩放比例
          </label>
          <div class="flex items-center space-x-2">
            <input
              type="range"
              min="0.1"
              max="3"
              step="0.1"
              v-model.number="currentScale"
              @input="handleScaleChange(handleInputNumber($event))"
              class="flex-1"
            />
            <span class="w-12 text-xs text-right text-gray-600">{{ currentScale.toFixed(1) }}x</span>
          </div>
        </div>

        <!-- 透明度 -->
        <div>
          <label class="block mb-1 text-xs font-medium text-gray-700">
            透明度
          </label>
          <div class="flex items-center space-x-2">
            <input
              type="range"
              min="0"
              max="1"
              step="0.1"
              v-model.number="currentOpacity"
              @input="handleOpacityChange(handleInputNumber($event))"
              class="flex-1"
            />
            <span class="w-12 text-xs text-right text-gray-600">{{ Math.round(currentOpacity * 100) }}%</span>
          </div>
        </div>
      </div>

      <!-- 文本标签页 -->
      <div v-if="tab === 'text'" class="space-y-3">
        <p class="text-xs text-gray-500">文本编辑功能</p>
        <p class="text-xs text-gray-400">此功能将在后续版本中实现</p>
      </div>

      <!-- 形状标签页 -->
      <div v-if="tab === 'shape'" class="space-y-3">
        <p class="text-xs text-gray-500">形状高级属性</p>
        <p class="text-xs text-gray-400">此功能将在后续版本中实现</p>
      </div>

      <!-- 操作按钮 -->
      <div class="pt-4 mt-6 border-t border-gray-200">
        <div class="grid grid-cols-2 gap-2">
          <button
            @click="handleDuplicateClick"
            class="px-3 py-2 text-xs transition-colors border border-gray-300 rounded hover:bg-gray-50"
          >
            复制
          </button>
          <button
            @click="handleDeleteClick"
            class="px-3 py-2 text-xs text-red-600 transition-colors border border-red-300 rounded hover:bg-red-50"
          >
            删除
          </button>
          <button
            @click="handleBringToFrontClick"
            class="px-3 py-2 text-xs transition-colors border border-gray-300 rounded hover:bg-gray-50"
          >
            置于顶层
          </button>
          <button
            @click="handleSendToBackClick"
            class="px-3 py-2 text-xs transition-colors border border-gray-300 rounded hover:bg-gray-50"
          >
            置于底层
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';

interface Props {
  selectedShape: any;
  manager?: any;
  onFillChange?: (color: string) => void;
  onStrokeChange?: (color: string) => void;
  onStrokeWidthChange?: (width: number) => void;
  onRotationChange?: (rotation: number) => void;
  onScaleChange?: (scale: number) => void;
  onOpacityChange?: (opacity: number) => void;
  onArrowChange?: (mode: 'none' | 'start' | 'end' | 'both') => void;
  onDelete?: () => void;
  onDuplicate?: () => void;
  onBringToFront?: () => void;
  onSendToBack?: () => void;
}

const props = defineProps<Props>();

const tab = ref<'style' | 'text' | 'shape'>('style');
const tabLabels: Record<string, string> = {
  style: '样式',
  text: '文本',
  shape: '形状'
};

// 响应式状态
const currentFillColor = ref('#3b82f6');
const currentStrokeColor = ref('#1e40af');
const currentStrokeWidth = ref(2);
const currentRotation = ref(0);
const currentScale = ref(1);
const currentOpacity = ref(1);
const fillEnabled = ref(true);
const strokeEnabled = ref(true);

// 从SVGElement中获取属性值
const getShapeAttribute = (attr: string, defaultValue: any) => {
  if (!props.selectedShape) return defaultValue;
  const value = props.selectedShape.getAttribute?.(attr);
  if (value === null || value === undefined) return defaultValue;

  // 类型转换
  if (attr === 'fill' || attr === 'stroke') return value;
  if (attr === 'stroke-width' || attr === 'rotation' || attr === 'opacity') {
    return parseFloat(value);
  }
  return value;
};

// 监听选中形状变化，更新属性值
watch(() => props.selectedShape, (newShape) => {
  if (!newShape) return;

  // 从SVG元素直接读取当前属性值
  currentFillColor.value = getShapeAttribute('fill', '#3b82f6');
  currentStrokeColor.value = getShapeAttribute('stroke', '#1e40af');
  currentStrokeWidth.value = getShapeAttribute('stroke-width', 2);
  currentRotation.value = getShapeAttribute('rotation', 0);
  currentScale.value = getShapeAttribute('scale', 1);
  currentOpacity.value = getShapeAttribute('opacity', 1);

  const fill = getShapeAttribute('fill', '#3b82f6');
  fillEnabled.value = fill !== 'transparent' && fill !== 'none';
  strokeEnabled.value = getShapeAttribute('stroke-width', 0) > 0;
}, { immediate: true });

// 事件处理函数
const handleTabChange = (newTab: string) => {
  tab.value = newTab as 'style' | 'text' | 'shape';
};

const handleInputValue = (event: Event) => {
  return (event.target as HTMLInputElement).value;
};

const handleInputNumber = (event: Event) => {
  return parseFloat((event.target as HTMLInputElement).value);
};

const handleFillChange = (color: string) => {
  currentFillColor.value = color;
  if (props.onFillChange) {
    props.onFillChange(color);
  }
};

const handleStrokeChange = (color: string) => {
  currentStrokeColor.value = color;
  if (props.onStrokeChange) {
    props.onStrokeChange(color);
  }
};

const handleStrokeWidthChange = (width: number) => {
  currentStrokeWidth.value = width;
  if (props.onStrokeWidthChange) {
    props.onStrokeWidthChange(width);
  }
};

const handleRotationChange = (rotation: number) => {
  currentRotation.value = rotation;
  if (props.onRotationChange) {
    props.onRotationChange(rotation);
  }
};

const handleScaleChange = (scale: number) => {
  currentScale.value = scale;
  if (props.onScaleChange) {
    props.onScaleChange(scale);
  }
};

const handleOpacityChange = (opacity: number) => {
  currentOpacity.value = opacity;
  if (props.onOpacityChange) {
    props.onOpacityChange(opacity);
  }
};

const handleDeleteClick = () => {
  if (props.onDelete) {
    props.onDelete();
  }
};

const handleDuplicateClick = () => {
  if (props.onDuplicate) {
    props.onDuplicate();
  }
};

const handleBringToFrontClick = () => {
  if (props.onBringToFront) {
    props.onBringToFront();
  }
};

const handleSendToBackClick = () => {
  if (props.onSendToBack) {
    props.onSendToBack();
  }
};
</script>

// src/components/PropertyPanel.tsx
"use client";

import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { cn } from '@/components/ui/utils';

export interface PropertyPanelProps {
  selectedShape: SVGElement | null;
  onFillChange?: (color: string) => void;
  onStrokeChange?: (color: string) => void;
  onStrokeWidthChange?: (width: number) => void;
  onRotationChange?: (rotation: number) => void;
  onScaleChange?: (scale: number) => void;
  onOpacityChange?: (opacity: number) => void;
  onDelete?: () => void;
  onDuplicate?: () => void;
  onBringToFront?: () => void;
  onSendToBack?: () => void;
}

export const PropertyPanel: React.FC<PropertyPanelProps> = ({
  selectedShape,
  onFillChange,
  onStrokeChange,
  onStrokeWidthChange,
  onRotationChange,
  onScaleChange,
  onOpacityChange,
  onDelete,
  onDuplicate,
  onBringToFront,
  onSendToBack,
}) => {
  const [fillColor, setFillColor] = useState('#3b82f6');
  const [strokeColor, setStrokeColor] = useState('#1e40af');
  const [strokeWidth, setStrokeWidth] = useState(2);
  const [rotation, setRotation] = useState(0);
  const [scale, setScale] = useState(1);
  const [opacity, setOpacity] = useState(1);
  const [tab, setTab] = useState<'style' | 'text' | 'shape'>('style');
  const [fillEnabled, setFillEnabled] = useState(true);
  const [strokeEnabled, setStrokeEnabled] = useState(true);

  // 从选中图形中提取属性
  useEffect(() => {
    if (!selectedShape) return;

    const fill = selectedShape.getAttribute('fill') || '#000000';
    const stroke = selectedShape.getAttribute('stroke') || '#000000';
    const strokeWidthAttr = selectedShape.getAttribute('stroke-width') || '2';
    const opacityAttr = selectedShape.getAttribute('opacity') || '1';

    const fillIsNone = fill === 'none';
    const strokeIsNone = stroke === 'none';

    setFillEnabled(!fillIsNone);
    setStrokeEnabled(!strokeIsNone);
    setFillColor(fillIsNone ? '#000000' : fill);
    setStrokeColor(strokeIsNone ? '#000000' : stroke);
    setStrokeWidth(parseFloat(strokeWidthAttr));
    setOpacity(parseFloat(opacityAttr));

    // 从transform中提取旋转和缩放
    const transform = selectedShape.getAttribute('transform') || '';
    const rotateMatch = transform.match(/rotate\(([^)]+)\)/);
    const scaleMatch = transform.match(/scale\(([^)]+)\)/);

    if (rotateMatch) {
      const angle = parseFloat(rotateMatch[1].split(' ')[0]);
      setRotation(angle);
    } else {
      setRotation(0);
    }

    if (scaleMatch) {
      const scaleFactor = parseFloat(scaleMatch[1]);
      setScale(scaleFactor);
    } else {
      setScale(1);
    }
  }, [selectedShape]);

  const handleFillChange = useCallback((color: string) => {
    setFillColor(color);
    onFillChange?.(color);
  }, [onFillChange]);

  const handleStrokeChange = useCallback((color: string) => {
    setStrokeColor(color);
    onStrokeChange?.(color);
  }, [onStrokeChange]);

  const handleStrokeWidthChange = useCallback((width: number) => {
    setStrokeWidth(width);
    onStrokeWidthChange?.(width);
  }, [onStrokeWidthChange]);

  const handleRotationChange = useCallback((angle: number) => {
    setRotation(angle);
    onRotationChange?.(angle);
  }, [onRotationChange]);

  const handleScaleChange = useCallback((scaleValue: number) => {
    setScale(scaleValue);
    onScaleChange?.(scaleValue);
  }, [onScaleChange]);

  const handleOpacityChange = useCallback((opacityValue: number) => {
    setOpacity(opacityValue);
    onOpacityChange?.(opacityValue);
  }, [onOpacityChange]);

  const presetColors = [
    '#ef4444', '#f97316', '#f59e0b', '#eab308', '#84cc16',
    '#22c55e', '#10b981', '#14b8a6', '#06b6d4', '#0ea5e9',
    '#3b82f6', '#6366f1', '#8b5cf6', '#a855f7', '#d946ef',
    '#ec4899', '#f43f5e', '#000000', '#6b7280', '#ffffff'
  ];

  const isText = useMemo(() => selectedShape?.tagName.toLowerCase() === 'foreignobject', [selectedShape]);

  if (!selectedShape) {
    return (
      <div className="w-72 bg-white border-l border-gray-200 p-4">
        <h3 className="text-lg font-semibold mb-4">属性面板</h3>
        <div className="text-gray-500 text-sm">
          选择一个图形来编辑其属性
        </div>
      </div>
    );
  }

  const shapeType = selectedShape.tagName.toLowerCase();

  return (
    <div className="w-72 bg-white border-l border-gray-200 p-0 flex flex-col">
      <div className="grid grid-cols-3 text-sm border-b border-gray-200">
        {(['style', 'text', 'shape'] as const).map(key => (
          <button
            key={key}
            className={cn(
              'py-2',
              tab === key ? 'bg-gray-100 font-semibold text-gray-800' : 'hover:bg-gray-50 text-gray-600'
            )}
            onClick={() => setTab(key)}
          >
            {key === 'style' ? '样式' : key === 'text' ? '文本' : '调整图形'}
          </button>
        ))}
      </div>

      <div className="p-4 overflow-y-auto space-y-4">
        {/* 样式 */}
        {tab === 'style' && (
          <div className="space-y-4">
            <div className="flex flex-wrap gap-2">
              {presetColors.slice(0, 16).map(color => (
                <button
                  key={color}
                  className="w-8 h-8 rounded border border-gray-200 shadow-sm"
                  style={{ backgroundColor: color }}
                  onClick={() => handleFillChange(color)}
                  title={color}
                />
              ))}
            </div>
            <div className="flex items-center gap-2">
              <input
                type="checkbox"
                checked={fillEnabled}
                onChange={(e) => {
                  setFillEnabled(e.target.checked);
                  if (e.target.checked) handleFillChange(fillColor);
                  else handleFillChange('none');
                }}
              />
              <span className="text-sm text-gray-700">填充</span>
              <Input
                type="color"
                value={fillColor}
                disabled={!fillEnabled}
                onChange={handleFillChange}
                className="w-10 h-8 ml-auto"
              />
            </div>

            <div className="flex items-center gap-2">
              <input
                type="checkbox"
                checked={strokeEnabled}
                onChange={(e) => {
                  setStrokeEnabled(e.target.checked);
                  if (e.target.checked) handleStrokeChange(strokeColor);
                  else handleStrokeChange('none');
                }}
              />
              <span className="text-sm text-gray-700">线条</span>
              <Input
                type="color"
                value={strokeColor}
                disabled={!strokeEnabled}
                onChange={handleStrokeChange}
                className="w-10 h-8 ml-auto"
              />
            </div>

            {shapeType !== 'text' && (
              <div className="flex items-center gap-2">
                <span className="text-sm text-gray-700">线宽</span>
                <Input
                  type="number"
                  value={String(strokeWidth)}
                  disabled={!strokeEnabled}
                  onChange={(value) => handleStrokeWidthChange(parseFloat(value || '0'))}
                  className="w-20"
                  min="0"
                  max="20"
                  step="0.5"
                />
              </div>
            )}

            <div className="space-y-2">
              <div className="flex items-center justify-between text-sm text-gray-700">
                <span>不透明度</span>
                <span>{Math.round(opacity * 100)}%</span>
              </div>
              <input
                type="range"
                min="0"
                max="1"
                step="0.01"
                value={opacity}
                onChange={(e) => handleOpacityChange(parseFloat(e.target.value))}
                className="w-full"
              />
            </div>
          </div>
        )}

        {/* 文本 */}
        {tab === 'text' && (
          <div className="space-y-3">
            <div className="flex items-center gap-2">
              <span className="text-sm text-gray-700">字体</span>
              <select className="flex-1 border border-gray-200 rounded px-2 py-1 text-sm bg-white" disabled={!isText}>
                <option>Helvetica</option>
                <option>Arial</option>
                <option>Roboto</option>
              </select>
            </div>
            <div className="flex items-center gap-2">
              <Button size="sm" variant="outline" disabled={!isText}>B</Button>
              <Button size="sm" variant="outline" disabled={!isText}><em>I</em></Button>
              <Button size="sm" variant="outline" disabled={!isText}><u>U</u></Button>
              <Input
                type="number"
                value="14"
                onChange={() => {}}
                className="w-16"
                disabled={!isText}
              />
            </div>
            <div className="text-xs text-gray-400">
              文本样式暂仅支持颜色/大小基础控件，更多文字编辑请双击文本直接编辑。
            </div>
          </div>
        )}

        {/* 调整图形 */}
        {tab === 'shape' && (
          <div className="space-y-3">
            <div className="grid grid-cols-2 gap-2">
              <Button size="sm" variant="outline" onClick={onBringToFront}>移至最前</Button>
              <Button size="sm" variant="outline" onClick={onSendToBack}>移至最后</Button>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-sm text-gray-700">旋转</span>
              <Input
                type="number"
                value={String(rotation)}
                onChange={(value) => handleRotationChange(parseFloat(value || '0'))}
                className="w-20"
                min="-180"
                max="180"
              />
              <span className="text-sm text-gray-500">°</span>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-sm text-gray-700">缩放</span>
              <Input
                type="number"
                value={String(scale)}
                onChange={(value) => handleScaleChange(parseFloat(value || '1'))}
                className="w-20"
                min="0.1"
                max="5"
                step="0.1"
              />
            </div>
            <div className="grid grid-cols-2 gap-2">
              <Button size="sm" variant="outline" onClick={onDuplicate}>创建副本</Button>
              <Button size="sm" variant="outline" onClick={onDelete}>删除</Button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default PropertyPanel;
